enum ProfileAttributes {
  NAME_ATTRIBUTE = 'NAME_ATTRIBUTE',
  OSID_ATTRIBUTE = 'OSID_ATTRIBUTE',
  CODE_ATTRIBUTE = 'CODE_ATTRIBUTE',
  URL_ATTRIBUTE = 'URL_ATTRIBUTE'
}

enum Onboarding {
  PROFILE_FACE_SCAN_COMPLETE = 'ONBOARDING_PROFILE_FACE_SCAN_COMPLETE',
  PROFILE_DETAILS_COMPLETE = 'ONBOARDING_PROFILE_DETAILS_COMPLETE',
}

enum Walkthrough {
  WALKTHROUGH_COMPLETE = 'WALKTHROUGH_COMPLETE'
}

enum ProfileFeedback {
  RATINGS_MAP = 'RATINGS_MAP',
  COMMENTS_MAP = 'COMMENTS_MAP'
}

const EXIT_DETECTED = 'EXIT_DETECTED';

export const PreferenceKeys = {
  ProfileAttributes,
  Onboarding,
  Walkthrough,
  ProfileFeedback,
  EXIT_DETECTED
};
